#!/bin/bash

function ejecutar(){

	clear

	modulo_principal

}

#########################################################
#			*** Menú Principal ***
#########################################################

function modulo_principal(){

	clear

	echo ""
	echo "----------------------------------------------"
	echo ""
	echo " Ingresar número para ejecutar Script Firewall."
	echo ""
	echo " [ 1 ] AUTORIZAR la salida de los servicios:"
	echo ""
	echo "		DNS / SAMBA / FTP"
	echo ""
	echo " [ 2 ] DENEGAR la salida de los servicios:"
	echo ""
	echo "		HTTP / NFS"
	echo ""
	echo " [ 3 ] VERIFICAR reglas anteriores."
	echo ""
	echo " [ 4 ] EJECUTAR regla especifica para bloquear"
	echo " acceso IP 192.168.50.20 y permitir el ingreso"
	echo " de los equipos de esa red, no así el ingreso"
	echo " de los equipos de otras redes."
	echo ""
	echo " [ 5 ] Salir."
	echo ""
	echo "----------------------------------------------"
	echo ""

	read -r opcion

	if [ "$opcion" = 1 ];

		then modulo_1
	fi

	if [ "$opcion" = 2 ];

		then modulo_2
	fi

	if [ "$opcion" = 3 ];

		then modulo_3
	fi
	
	if [ "$opcion" = 4 ];

		then modulo_4
	fi

	if [ "$opcion" = 5 ];

		then modulo_salir
	fi

}

#########################################################
#				*** Funcion Modulo 1 ***
#########################################################

function modulo_1(){

# DNS

	iptables -A OUTPUT -p tcp --dport 43 -j ACCEPT
	iptables -A OUTPUT -p udp --dport 53  -j ACCEPT
	
# FTP

	iptables -A OUTPUT -p tcp --dport 21 -j ACCEPT
	
# SAMBA

	iptables -A OUTPUT -p udp --dport 137 -j ACCEPT
	iptables -A OUTPUT -p udp --dport 138 -j ACCEPT
	iptables -A OUTPUT -p tcp --dport 139 -j ACCEPT
	iptables -A OUTPUT -p tcp --dport 445 -j ACCEPT

	service iptables save

	clear
	
	echo " Reglas aplicadas."
	
	read -rsp $' Presiona cualquier tecla para volver.\n' -n 1 key
	
	modulo_principal

}

#########################################################
#				*** Funcion Modulo 2 ***
#########################################################

function modulo_2(){

# HTTP

	iptables -A OUTPUT -p tcp --dport 80 -j DROP

# NFS

	iptables -A OUTPUT -p tcp --dport 2049 -j DROP
	iptables -A OUTPUT -p udp --dport 2049 -j DROP
	
	service iptables save

	clear
	
	echo " Reglas aplicadas."
	
	read -rsp $' Presiona cualquier tecla para volver.\n' -n 1 key
	
	modulo_principal

}

#########################################################
#				*** Funcion Modulo 3 ***
#########################################################

function modulo_3(){

	clear
	
	iptables -nvL | grep ACCEPT
	iptables -nvL | grep DROP
	iptables -S | grep INPUT
	iptables -S | grep OUTPUT

	echo ""
	read -rsp $' Presiona cualquier tecla para volver.\n' -n 1 key
	echo ""

	modulo_principal

}

#########################################################
#				*** Funcion Modulo 4 ***
#########################################################

function modulo_4(){

	clear

	iptables -I INPUT -p tcp -s 192.168.50.0/24 -d 192.168.50.0/24 -j ACCEPT
	iptables -A INPUT -p tcp -d 192.168.50.0/24 -j DROP
	iptables -I INPUT -p tcp -s 192.168.50.0/24 -d 192.168.50.0/24 -j ACCEPT
	iptables -A INPUT -p tcp -d 192.168.50.0/24 -j DROP
	iptables -A INPUT -p tcp -s 192.168.50.20 -d 192.168.50.0/24 -j DROP
	
	echo " Reglas aplicadas."

	read -rsp $' Presiona cualquier tecla para volver.\n' -n 1 key

	modulo_principal

}

#########################################################
#				*** Función Salir ***
#########################################################

function modulo_salir(){

	clear

	exit 0

}

#########################################################
#					*** FIN ***
#########################################################

clear

ejecutar
